cognitedata/power-ops-sdk

cognite/powerops/case/__init__.py, cognite/powerops/client/shop_api.py, cognite/powerops/utils/cdf_utils.py, examples/run_results.py, examples/trigger_shop_run.py
=> Powerops 1211 shop run results

cognite/powerops/client/powerops_client.py, cognite/powerops/client/shop_api.py, examples/run_results.py
=> Add objective_function to run results

.github/workflows/build.yml, .readthedocs.yaml, cognite/powerops/config.py, docs/index.md, docs/reference.md, mkdocs.yml, poetry.lock, pyproject.toml
=> POWEROPS-1276: Setup docs

cognite/powerops/preprocessor/cogreader.py, tests/test_bootstrap/data/demo/fornebu/cog_shop_files_config.yaml, tests/test_bootstrap/data/demo/watercourses_shop.yaml, tests/test_preprocessor/test_cog_shop_file.py
- Raise errors instead of returning empty file dict
- Add validation to sort_by field
- Update tests to assert exception is raised
=> Preprocessor bugfix

tests/test_unit/test_bootstrap/approval_test/mock_resource_create_classes.py, tests/test_unit/test_bootstrap/approval_test/test_apply.py, tests/test_unit/test_bootstrap/approval_test/test_apply/demo.yml
=> refactor: extended approval test with instances

.github/renovate.json, .pre-commit-config.yaml, poetry.lock, tests/test_unit/test_preprocessor/test_cog_shop_file.py
=> Calm renovate

cognite/powerops/resync/models/base.py, cognite/powerops/resync/models/market/base.py, cognite/powerops/resync/models/market/benchmark.py, cognite/powerops/resync/models/market/dayahead.py, cognite/powerops/resync/models/market/rkom.py, cognite/powerops/resync/to_models/to_market_model.py, cognite/powerops/resync/to_models/to_production_model.py, tests/test_unit/test_bootstrap/approval_test/test_apply.py
=> tests: Split approval test into summary and details

cognite/powerops/cli.py
=> refactor: Calm cognite-sdk logger

.pre-commit-config.yaml, cognite/powerops/clients/shop/api/shop_results_api.py, poetry.lock
=> refactor: upgrade

cognite/powerops/clients/shop/_api_client.py, cognite/powerops/clients/shop/api/shop_api.py, cognite/powerops/clients/shop/api/shop_result_files_api.py, cognite/powerops/clients/shop/api/shop_results_api.py, cognite/powerops/clients/shop/api/shop_run_api.py, cognite/powerops/clients/shop/data_classes/shop_model.py, cognite/powerops/clients/shop/data_classes/shop_result_files.py, cognite/powerops/clients/shop/data_classes/shop_results.py, cognite/powerops/clients/shop/data_classes/shop_run.py, docs/reference/client/shop_api.md, docs/reference/client/shop_api_classes.md, mkdocs.yml, pyproject.toml
=> Setup docs

tests/test_integration/resync/test_plan.py
Added `.secrets.toml`, because by default `settings.toml` has a device-code login flow, which doesn't work for tests.
=> Running test_plan unit test locally

cognite/powerops/transformations/transformations.py
`pytest` is configured to actually run doctests as well. This PR fixes this doctest.
Note: GitHub workflow runs only a subset of tests (for now, [I hope](https://github.com/cognitedata/power-ops-sdk/pull/183) we will change this at some point)
=> fix a doctest

cognite/powerops/resync/config/_main.py, cognite/powerops/resync/config/production/generator.py, cognite/powerops/resync/config/production/watercourse.py, cognite/powerops/resync/models/v1/config_to_model/to_production_model.py, poetry.lock, tests/data/demo/production/fornebu/model_raw.yaml, tests/test_unit/test_resync/approval_test/test_apply/demo_CogShop1Asset.yml, tests/test_unit/test_resync/approval_test/test_apply/demo_ProductionModel.yml
=> Generator Validation

scripts/upgrade_sdk_customers.py
=> fix; script to main as default branch in all repos

cognite/powerops/transformations/transformations.py, docs/packages/transformations/transformations.md
=> new transformation for adding sevral timeseries together

tests/data/demo/settings.yaml, tests/test_unit/test_resync/approval_test/test_apply/demo_CogShop1Asset.yml
Output from plan:
* **sequences**: 0 added, 0 removed, 0 changed
* **files**: 0 added, 0 removed, 0 changed
* **timeseries**: **2 added**, 0 removed, 0 changed
* **assets**: 0 added, 0 removed, 0 changed
* **relationships**: 0 added, 0 removed, 0 changed
* **parent_assets**: 0 added, 0 removed, 0 changed
* **labels**: 0 added, 0 removed, 0 changed
* **nodes**: 0 added, **3 removed**, **3 changed**
* **edges**: 0 added, **8 removed**, 0 changed
=> Shop version staging

poetry.lock, pyproject.toml, scripts/write_read_instances.py
=> [POWEROPS-2102] Test read write instances

cognite/powerops/resync/models/v2/powerops_models.py
=> fix: logic for finding view dependencies

cognite/powerops/custom_modules/power_model_v1/data_models/compute_TotalBidCalculation.datamodel.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/compute_WaterValueBasedDayAhead.datamodel.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/config_DayAheadConfiguration.datamodel.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/frontend_Asset.datamodel.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/frontend_DayAheadBid.datamodel.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/node_types/power-ops-types.node.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/views/assets/PriceAreaAsset.view.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/views/function_outputs/TotalBidMatrixCalculationOutput.view.yaml
=> Party branch

cognite/powerops/custom_modules/power_model_v1/data_models/views/scenario/1-interface.ScenarioBase.view.yaml, cognite/powerops/resync/core/main.py, cognite/powerops/resync/models/v2/powerops_models.py
=> Fix double use of container

cognite/powerops/custom_modules/power_model_v1/data_models/views/bid_configuration/1-interface.BidConfiguration.view.yaml, scripts/write_read_instances.py
=> fix: bid config view

cognite/powerops/custom_modules/power_model_v1/data_models/views/bid_method/1.interface.BidMethodDayAhead.view.yaml, scripts/write_read_instances.py
=> fix: bidmethod

cognite/powerops/custom_modules/power_model_v1/data_models/views/bid_method/1.interface.BidMethodDayAhead.view.yaml, scripts/write_read_instances.py
=> Bidmethod fix

cognite/powerops/cognite_modules/_system.yaml, poetry.lock, pyproject.toml
=> build; toolkit 0.1.1

.pre-commit-config.yaml
=> fix: remove no-commit-to-branch since pre-commit runs on PR merge

CONTRIBUTING.md, cognite/powerops/cognite_modules/_system.yaml, cognite/powerops/config.dev.yaml, cognite/powerops/config.heco-dev.yaml, cognite/powerops/config.lyse-dev.yaml, cognite/powerops/config.staging.yaml, cognite/powerops/custom_modules/power_model_v1/data_models/containers/FunctionData.container.yaml
=> feat: added env specific configs

CHANGELOG.md, cognite/powerops/resync/v1/config_to_fdm.py, cognite/powerops/resync/v1/main.py, cognite/powerops/utils/serialization.py
Fixed a few bugs detected when running resync V1 for Lyse, ref. [this Jira ticket](https://cognitedata.atlassian.net/browse/POWEROPS-2435)
Want to merge this into the resync-data-update-mappings branch to avoid another deployment and version bump because that one also contains a small improvement to resync V1
=> Resync v1 fixes

tests/data/demo/v1/fornebu/shop_scenario.yaml
=> link output definitions to scenarios

scripts/write_read_instances.py
=> chore: update clean up script

.github/workflows/resync-apply.yaml, .github/workflows/resync-plan.yaml, settings.toml, tests/data/demo/v1/resync_configuration.yaml
=> feat: add workflows for resync v1 plan/apply

tests/data/demo/v1/fornebu/bid_configuration_day_ahead.yaml, tests/data/demo/v1/shared/date_specification.yaml
(and adding more DateSpecifications)
=> Changing processing_timezone to Europe/Oslo 

.github/renovate.json
=> fix: point to public renovate config to extend

poetry.lock, pyproject.toml, toolkit/_system.yaml
=> chore: update toolkit version

CONTRIBUTING.md, toolkit/config.dev.yaml, toolkit/config.heco-dev.yaml, toolkit/config.heco-prod.yaml, toolkit/config.lyse-dev.yaml, toolkit/config.lyse-prod.yaml, toolkit/config.staging.yaml
=> [POWEROPS-2598] feat: setup prod toolkit configs

poetry.lock, pyproject.toml, toolkit/_system.yaml, toolkit/config.dev.yaml, toolkit/config.heco-dev.yaml, toolkit/config.heco-prod.yaml, toolkit/config.lyse-dev.yaml, toolkit/config.lyse-prod.yaml, toolkit/config.staging.yaml
=> chore: update toolkit version to 0.2.16 and remove redundant name in configs

.codespellrc, .pre-commit-config.yaml, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, cognite/powerops/client/shop/api/dayahead_trigger_api.py, cognite/powerops/resync/core/main.py, cognite/powerops/resync/models/_shared_v1_v2/cogshop_model.py, cognite/powerops/resync/time_series_mapping/__init__.py, docs/index.md, docs/quickstart/data_engineer.md, pyproject.toml, scripts/backup/power-ops-afrr-bids-AFRRBids-v1.graphql, scripts/create_multi_scenario_bid_processes.py, tests/test_integration/resync/test_serialization_sha256.py, toolkit/custom_modules/power_model_v0/data_models/views/baseBids-Alert.view.yaml, toolkit/custom_modules/power_model_v1/data_models/views/alerts/1-interface.Alert.view.yaml
=> chore: configure and fix spell checker pre-commit

CONTRIBUTING.md, toolkit/config.oe-dev.yaml, toolkit/config.oe-prod.yaml
=> feat: configure DM for oe

toolkit/config.heco-dev.yaml, toolkit/config.heco-prod.yaml, toolkit/config.lyse-dev.yaml, toolkit/config.lyse-prod.yaml, toolkit/config.oe-dev.yaml, toolkit/config.oe-prod.yaml
=> rename toolkit variable name

cognite/powerops/utils/cdf/calls.py, poetry.lock, pyproject.toml, toolkit/cdf.toml, toolkit/config.staging.yaml, toolkit/modules/power_ops_template/workflows/bid_process_triggers.WorkflowTrigger.yaml
=> fix: wf trigger metadata

RESYNC.md, scripts/mapping.ipynb
=> Update file references in RESYNC.md

.github/workflows/toolkit-deploy.yaml
=> fix: workflow variable reference
